### ISSUE TITLE
PIC24FJ

### ISSUE THREAD

**Issue by fabioriksilva** [jaromir-sukuba/a-p-prog#8]
Is it possible make some changes in this project to add 24FJ(16bit) processors?
  Today, I'm using ARM in 90% of my projects, cause of that I have made a pattern writer in all my projects using the DAPlink project as: https://github.com/ARMmbed/DAPLink.
 
   This project has an usart CDC implemented, that runs very well.

    So, I would like tho know if you can helping me to put up the model:
    PIC24FJ128GC010
    https://www.microchip.com/wwwproducts/en/PIC24FJ128GC010

    I really would appreciate your help, as I just starting with github projects.

   Thank you so much!

**Comment by jaromir-sukuba** [comment]
Hello,
from technical point of view, there is nothing stopping from adding 16-bit MCU support and at some point in the project I thought of adding it, however I decided no to do it, because:
1, Programmer is slow (theoretical limit is 5kB/s, however it's less in practice due to simple buffering). 8-bitters do usually have less of FLASH than 16-bit ones, so this slow-ness isn't that much of a problem.
2, There isn't open source compiler for 16-bit PICs. This simple open-source programmer is good match to SDCC.
Users using XC16 can also use rest of Microchip's ecosystem with their programmers, being MUCH faster than this arduino based one.
3, It's quite bit of work and adding it into my spaghetti code wouldn't be pleasing experience.

The programmer software and firmware would need at least major rewrite in order to become half-usable 16-bit PIC programmer. Ideally, hardware rework would be advisable, because this started as one-off quick project and grown much out of original scope.
So, for now the answer is no, but I'm open to pull requests.
